---
layout: post
title: "Simulation-based Science: Breaking Boundaries"
date: 2021-07-18 11:30:00 +0100
# categories: R
status: process
published: true
# status: development
# published: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = 'center', fig.width = 8, fig.height = 6)
```


Simulations are integral to many scientific disciplines and inquiries. I was therefore delighted when Mike Lees asked me to organize --- [together with](https://www.sbscommunity.nl/sbs-organization/) Eric Dignum, Alex Gabel, Christian Spieker, Anna Keuchenius, and Vitor Vasconcelos --- the Simulation-based Science colloquium for the summer semester 2021. The colloquium is usually hosted at the [Institute for Advanced Study](https://ias.uva.nl/), but it is on Zoom that we met weekly. We split the task of inviting speakers amongst ourselves, and created what I think is an impressive line-up of 18 speakers with a wide range of backgrounds. All talks except the first one have been recorded and are available on [YouTube](https://www.youtube.com/watch?v=wutFo9c6QmU&list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&index=1) (see [here](https://www.sbscommunity.nl/past-events/) for a short description of all talks).

I am at a psychology department --- the Department of Psychological Methods at the University of Amsterdam --- and one reason why I was asked to help organize the colloquium might have been to find good speakers from psychology or closely related fields.

## Psychology?
I did little to advance this goal. The closest I got to was inviting my colleague [Maarten van den Ende](https://www.iops.nl/students/current-iops-students/maarten-van-den-ende/) to briefly [speak about](https://youtu.be/xfTp71vw-io?list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&t=53) his excellent work on modelling of psychological and social dynamics of urban mental health conditions. To facilitate this type of work, Mathijs Maijer and Maarten have developed an impressive [Python package](https://github.com/Tensaiz/DyNSimF) that you may find useful for your own projects. While Maarten pursues psychological topics, he takes a distinctly interdisciplinary approach.

If gracious, you might say that inviting [Paul Smaldino](https://smaldino.com/wp/) counts, who is well-known in psychology and who repeatedly and forcefully articulated the usefulness of formal modelling (e.g., Smaldino, [2017](https://smaldino.com/wp/wp-content/uploads/2017/01/Smaldino2017-ModelsAreStupid.pdf), [2019](https://pubmed.ncbi.nlm.nih.gov/31695216/)). A core problem of psychology is its curriculum, and Smaldino ([2020](https://www.tandfonline.com/doi/full/10.1080/1047840X.2020.1853463)) lays out the importance of increasing interdisciplinarity, technical skill, and philosophical scrutiny. Having stopped studying psychology after my undergraduate degree because of a lack of mathematical training and the fact that lectures and published psychological papers were often just a series of non sequiturs, it is good to see these issues articulated so well in print.

In his talk, Paul eschewed distinctly psychological content, however, and instead [talked about his recent work](https://www.youtube.com/watch?v=yktdQ0yiYOw&list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&index=7) on how interdisciplinarity can spread better methods (Smaldino & O'Connor, [2020](https://osf.io/preprints/metaarxiv/cm5v3/)). (Paul also showed an excerpt from what is probably my favourite [Noam Chomsky interview](https://www.youtube.com/watch?v=GjENnyQupow)).

The argument is as simple as it is compelling: having people from other disciplines take a critical look at the work a particular field is doing may help that field discover more quickly whether it is stuck in a local optimum. Local optimum may be too charible a phrase, however. Paul mentions the case of "magnitude-based inference" in sports science, a statistical method which was not described in equations but distributed as an Excel spreadsheet, wrecking havoc after its introduction.

For disciplines (overly) focused on empirical work such as psychology, statisticians are a natural outside group to assess the sensibilities of the field's inferences. From a bigger picture perspective, however, conversations with anthropologists, philosophers, physicists, economists, ecologists, etc. may be even more insightful. They certainly would be more fun. Unfortunately, few [places exist](https://ias.uva.nl/content/news/2021/06/a-walk-through-research-at-the-uva-institute-for-advanced-study.html) exist where such [mingling is encouraged](https://www.santafe.edu/engage/learn/programs/sfi-complex-systems-summer-school).


## Automation
The first speaker I invited was [Maria del Rio-Chanona](https://mariadelriochanona.info/), who gave a [fantastic talk](https://www.youtube.com/watch?v=8Aqi6U3C4i4&list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&index=5) about her work on occupational mobility and automation (del Rio Chanona et al., [2021](https://royalsocietypublishing.org/doi/full/10.1098/rsif.2020.0898)). At the core of this work is an *occupational mobility network*, a directed and weighted network whose nodes are occupations and whose weights give the probability that a worker transitions between occupations (and which is calibrated using US data). Running an agent-based model on this network and using estimates of the potential for automation of different occupations, Maria and her colleagues explored the effect of automation shocks. These shocks reallocate labour in the economy, increasing demand for it in occupations with a low potential for automation and decreasing demand for it in occupations with a high potential for automation.

A key finding is that the impacts on workers do not only depend on the automatability of their current occupation, but also on the automatability of occupations they could transition into. For example, 'statistical technicians' have a much higher probability of being automated than childcare workers, yet the prospects of long-term unemployment are worse for the latter. The authors note that this is because it is relatively easy for statistical technicians to transfer into occupations that increase in demand. On the flipside, it is relatively easy for workers in occupations that are susceptible to automation to transfer into childcare work, increasing those workers' supply relative to their demand. As this example shows, and as Maria and colleagues argue more generally, network effects are more likely to hurt workers in low-income occupations, while workers in high-income occupations are more likely to benefit.

Together with colleagues, Maria also used her agent-based network model to assess the impacts of COVID-19 on the labour market in a paper that I found a very illuminating as the pandemic got going in early 2020 (del Rio Chanona et al., [2020](https://academic.oup.com/oxrep/article/36/Supplement_1/S94/5899019)). Agent-based models are a key tool in *complexity economics* (Farmer & Foley, [2009](https://www.nature.com/articles/460685a); Arthur, [2021](https://www.nature.com/articles/s42254-020-00273-3)), a field that aims to provide a more realistic perspective on the economy --- and, as far as my experience goes, also makes for very enjoyable papers.

When I asked Maria why her paper on automation was not published in an economics journal, she was (rightfully) a bit taken aback, saying that she considers this work interdisciplinary --- an econ journal just would not do.


## Tipping points
I then invited [Jonathan Donges](https://www.pik-potsdam.de/members/donges/homepage), who gave a truly [wide-ranging and impressive talk](https://www.youtube.com/watch?v=TBtIyoNoj-E&list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&index=8), summarizing the work he did and is doing together with colleagues at the Potsdam Institute for Climate Impact Research on tipping points in the climate system and in the social sphere.

Jonathan noted that there exist considerable uncertainties in climate tipping elements pertaining to their exact thresholds and the strength and sign of their interactions. At the same time, tipping elements are not fully represented in state-of-the-art Earth system models, which are also too slow to run large-scale ensemble simulations with that are required for a risk analysis under large uncertainties. This motivates a simplified modelling approach that captures the essence of tipping elements and their interactions, which Jonathan and others found in the coupling of cusp catastrophes on complex networks (e.g., Klose et al., [2019](https://royalsocietypublishing.org/doi/full/10.1098/rsos.200599); Krönke et al., [2020](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.101.042311)). Using this approach, Wunderling et al. ([2021](https://esd.copernicus.org/articles/12/601/2021/)) studied four tipping elements and found that interactions between them tend to destabilize the system, implying [significant risk of tipping cascades](https://www.theguardian.com/environment/2021/jun/03/climate-tipping-points-could-topple-like-dominoes-warn-scientists) already at 2°C.

Tipping points are usually defined in terms of critical *thresholds*: going above a critical level of, say, temperature causes the system to transition into an alternative stable state. However, systems can also tip when a critical *rate* is exceeded (for an excellent introduction, see Siteur et al. [2016](https://onlinelibrary.wiley.com/doi/abs/10.1111/oik.03112)). I [asked Jonathan](https://www.youtube.com/watch?v=TBtIyoNoj-E&list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&t=4160s) whether this type of tipping is something that needs more attention since the rate of temperature increase --- and not only its absolute level --- is also extraordinary, while at the same time the Paris climate agreement and other policy frameworks only define critical thresholds. Jonathan replied that the lack of consideration of critical rates is indeed problematic, and that there is more evidence accumulating suggesting that rate-induced tipping can occur in climate tipping elements (e.g., Lohmann & Ditlevsen, [2021](https://www.pnas.org/content/118/9/e2017989118.short)). He also mentioned, anecdotally, that Hans Joachim Schellnhuber --- [founding director of PIK](https://www.pnas.org/content/105/6/1783) --- proposed to consider both critical thresholds as well as critical rates already in the 1990s; however, rates were thrown out because it was considered too complicated for politicians. During a similar discussion, Schellnhuber [confirmed this anecdote](https://youtu.be/AAGQHPbsvTY?t=2282) at an all-star panel on tipping points. (I noticed later that this is actually also described in Schellnhuber, Rahmstorf, & Winkelmann, [2016](https://www.nature.com/articles/nclimate3013#Sec3)).

As Jonathan pointed out, while we have some understanding of the tipping dynamics in the climate system, our understanding of tipping dynamics in the social domain is much more limited. For example, it is relatively straightforward to map the important drivers for climate tipping points on global temperature increase; but it is basically impossible to map dramatic changes in, say, public opinion on any single driver. Winkelmann, Donges, et al. ([2020](https://arxiv.org/abs/2010.04488)) discuss the differences between physical and social tipping processes in great detail. Milkoreit et al. ([2018](https://iopscience.iop.org/article/10.1088/1748-9326/aaaa75/meta)) present a fascinating study of the term *tipping point* as it pertains to the physical and the social domain. Otto, Donges, et al. ([2020](https://www.pnas.org/content/117/5/2354/)) describe twelve social tipping elements that may help us achieve rapid decarbonization. Interestingly, this work inspired a [Dutch initiative](https://socialtippingpointcoalitie.nl/social-tipping-point-coalition/) pushing politicians to use these insights to transform society.

There are too many excellent papers on these topics coming out of PIK to link to here. What is clear, however, is that integrating the thinking about physical tipping points with the thinking about social tipping processes requires researchers with different backgrounds. When I asked Jonathan about his work on including human dynamics into Earth system modelling (Donges, Heitzig, et al., [2020](https://esd.copernicus.org/articles/11/395/2020/)), for example, he [stressed the importance](https://youtu.be/TBtIyoNoj-E?list=PLy66Zw8nf6kC33svRPje6jSuHwwP6_Y8I&t=4457) of interdisciplinary collaboration and that, in the past, the modelling was carried out primarily by physicists without a deep understanding of the social sciences; at the same time, social scientists usually lack the relevant modelling skills, making collaboration and cross-disciplinary education essential.


## Ecosystem resilience
The next speaker I invited was [Juan Rocha](https://www.juanrocha.se/), who [talked about his work](https://www.youtube.com/watch?v=57rJ4N0yPXw) on detecting resilience loss in ecosystems, and on how people behave when faced with the knowledge about thresholds. From a whole Earth system perspective, we are transgressing a number of planetary boundaries (Rockström et al., [2009](https://www.jstor.org/stable/26268316); Steffen et al., [2015](https://science.sciencemag.org/content/347/6223/1259855.abstract)), with the climate crisis getting most of the attention. As [The Economist](https://www.economist.com/technology-quarterly/2021/06/15/loss-of-biodiversity-poses-as-great-a-risk-to-humanity-as-climate-change) noted recently, biodiversity loss and ecosystem collapse are crises of similar magnitude, yet receive a fraction of the public attention (see also [here](https://www.economist.com/podcasts/2021/06/22/can-technology-help-solve-the-biodiversity-crisis) and, if you are interested, our recent [CorrelAid Netherlands event](https://correlaid.nl/blog/conserving-nature/) with three Dutch NGOs on conserving nature). One key reason behind this imbalance is the fact that it is much more challenging to assess the health of ecosystems than to assess the (global) state of the climate, where measures such as CO$_2$ parts per million and degrees above average pre-industrial temperatures are easily tracked.

In his work, Juan used so-called *resilience indicators* based on [dynamical systems theory](https://fabiandablander.com/r/Dynamical-Systems.html) to assess the extent to which ecosystems world-wide are at risk of critical transitions. In this Herculean effort, which Juan [recently preprinted](https://arxiv.org/abs/2107.03307), he used proxies for primary productivity of marine and terrestrial ecosystems measured weekly at a spatial resolution of 0.25° (i.e., areas of about 28 square kilometres) from around 2000 to 2018. Computing the resilience indicators, Juan found that up to 29% of terrestrial and 24% of marine ecosystems are showing symptoms of resilience loss. Further statistical analyses revealed that this resilience loss is due to a combination of slow forcing and stochasticity in environmental variables such as temperature, precipitation, and sea surface salinity. It would indeed be excellent if, as Juan suggests, this work would pave the way towards a planetary ecological resilience observatory.


## Climate conundrums
The last speaker I invited was [Philip Stier](https://www.physics.ox.ac.uk/our-people/stier), who gave an excellent talk on climate models and the associated uncertainties. I first heard Philip speak at the [Oxford School of Climate Change](https://www.oxfordclimatesociety.com/the-oxford-school-of-climate-change.html) (whose organizing society runs a [fantastic YouTube channel](https://www.youtube.com/channel/UCOoksFYBCHqZWwVBU9qewZg)), where he introduced the basics of climate change to hundreds of people from across the world. [In his Simulation-based Science talk](https://www.youtube.com/watch?v=7q2bzkl5pd0), Philip walked us through climate models --- from zero-dimensional box models to the widely used General Circulation models --- noting that climate models are actually not that perfect (Palmer & Stevens, [2019](https://www.pnas.org/content/116/49/24390.short)). A substantial amount of uncertainty is due to clouds and aerosols and their interaction, which is only partially resolved in the current generation of climate models. There is a next generation of climate models on the horizon that can address these uncertainties better by increasing the resolution to be in the kilometres range; the biggest challenges for these models are then computational.

In preparation for Philip's talk, I stumbled upon the Lelieveld et al. ([2019](https://www.pnas.org/content/116/15/7192)) paper, which I thought was harrowing: air pollution due to fossil fuels kills about 4 million people per year, yet these aerosols cause significant cooling. Removing fossil fuel generated aerosols (which are short-lived) would save millions of lives annually, and also increase rainfall in regions where it would be very welcome, increasing food and water security. Yet removing these aerosols would also increase global mean temperature by about 0.51(±0.03) °C in the near-term, if we leave greenhouse gases unchanged. If we reduce airpollution and greenhouse gases concurrently, we can reduce this warming to 0.36(±0.06) °C.

This issue is well known, at least in the climate modelling community. Philip mentioned earlier work on modeling the aerosol cooling effect, which demonstrated the same conundrum (Brasseur & Roeckner, [2005](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2005GL023902)). He noted that this vexing issue makes it *much harder* to stay within 1.5 °C of warming. Lelieveld et al. ([2019](https://www.pnas.org/content/116/15/7192)) agree, writing that their "results suggest that it is very unlikely that the 1.5 °C target is achieved this century without massive CO$_2$ extraction from the air." The only 'consolation' I could get from Philip when discussing this with him was that cleaning up air pollution will take time, and so the warming will not be instant. But it will be there.


## Conclusion: Breaking boundaries
Above I provided some reflections on the talks from speakers I personally invited. We did have a number of other excellent speakers, however, with topics ranging from the role of simulations in COVID-19 research and robotics to refining causal loop diagrams and portfolio risk modelling. I encourage you to browse through the list of our [past events](https://www.sbscommunity.nl/past-events/) and see what peaks your interest.

We are currently [breaking multiple planetary boundaries](https://www.imdb.com/title/tt14539726/), pushing the Earth into a state last seen millions of years ago. Uncertainties about what this trajectory will bring abound, even at a 'mere' 1.1 °C of warming. The only thing that is certain is that we need to radically change course to avoid the worst outcomes.

This has implications also for how we organize science, with psychology possibly playing a key role in this new era. Psychology, after all, is the science of the mind and *behaviour*, and it is human behaviour that is causing our multiple interlinked crises. This does not mean that psychologists are particularly well poised to engage in this kind of work, however. Little progress is made within isolated university departments on issues that transcend disciplinary boundaries, and the usual academic training ill-equips psychologists to talk to fields that are more mathematized. That said, there is ample space for empirical psychological work, but I am unaware of any sizeable fraction of psychologists engaging with these topics at a level that is commensurate with the threats that lie ahead. (Please email me if you can correct this (mis)perception.)

To address the climate and ecological crises requires an all-hands-on-deck and thus necessarily interdisciplinary approach. I am glad that places like the Institute for Advanced Study exist, places that are not bound by outdated disciplinary structures and that can foster broad collaborations and coalitions.

I thoroughly enjoyed co-organizing this iteration of the Simulation-based Science colloquium, and I am looking forward to seeing what future organizers will cook up!


----
*I want to thank [Eric Dignum](https://www.uva.nl/en/profile/d/i/e.p.n.dignum/e.p.n.dignum.html), [Alex Gabel](https://ivi.fnwi.uva.nl/vislab/author/alex-gabel/), [Christian Spieker](https://nl.linkedin.com/in/christian-spieker-87558118b), [Anna Keuchenius](https://www.uva.nl/en/profile/k/e/a.keuchenius/a.keuchenius.html), [Vitor Vasconcelos](https://twitter.com/VVLVasconcelos), and [Mike Lees](https://twitter.com/mhlees) for being a great team and [Joyce Ten Holter](https://nl.linkedin.com/in/joyce-ten-holter) and [Charlotte van de Wijngaert](https://nl.linkedin.com/in/charlotte-van-de-wijngaert-03646417a) from the Institute for Advanced Study for organizational help and support.*
